name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
      - run: bun run build
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist
          
      - uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: github-pages
